name = "SWPRegistry"
uuid = "912938a2-aad1-4419-9dd4-32a10dcac77a"
repo = "https://github.com/warisa-r/SWPRegistry.git"
description = "My registry for an SWP project"

[packages]
a75b99cc-be56-4638-99bc-d89fa43b9ca1 = { name = "ShockwaveDetection", path = "S/ShockwaveDetection" }
